### ISSUE TITLE
Support auto tracking

### ISSUE THREAD

**Issue by Klemensas** [Klemensas/seenit-server#131]
Add an option to track items automatically without any popups.
These items should have a special status or stored differently and should need additional confirmation. before appearing as watched.

- [ ] Add server saving of auto tracked items, these should have extra metadata for handling unidentified items
- [ ] Add server support for confirming or discarding these items
- [ ] Add extension auto-tracking
- [ ] Add desktop auto-tracking
- [ ] Add display and management of auto tracked items
